package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class detail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(1);
    _jspx_dependants.add("/public/head.jspf");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n<html>\r\n<head>\r\n\t");
      out.write('\n');
      out.write('\n');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\n<title>易购商城</title>\n<!-- 下面是前端页面的样式 -->\n<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${shop }", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/css/public.css\" />\n<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${shop }", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/css/style.css\" />\n<!-- 下面是easyui的环境 -->\n<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${shop }", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/jquery-easyui-1.3.5/themes/icon.css\" type=\"text/css\"></link>\n<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${shop }", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/jquery-easyui-1.3.5/themes/default/easyui.css\" type=\"text/css\"></link>\n<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${shop }", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/jquery-easyui-1.3.5/jquery.min.js\"></script>\n<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${shop }", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/jquery-easyui-1.3.5/jquery.easyui.min.js\"></script>\n<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${shop }", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/jquery-easyui-1.3.5/locale/easyui-lang-zh_CN.js\"></script>\n");
      out.write("\r\n\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${shop}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/css/detail.css\" />\r\n</head>\r\n<body>\r\n    <div class=\"wrapper\">\r\n        <div class=\"header\">\r\n            <div class=\"header_container\">\r\n                <!--头部开始-->\r\n                <div class=\"top_bar clear\">\r\n                    <!--头部小导航-->\r\n                    <div class=\"welcom fl\">欢迎光临LEISUPET SHOP!</div>\r\n                    <ul class=\"top_links fr\">\r\n                        <li><a href=\"#\">首页</a></li>\r\n                        <li><a href=\"#\">我的账户</a></li>\r\n                        <li><a href=\"#\">购物车</a></li>\r\n                        <li><a href=\"#\">注册</a></li>\r\n                        <li ><a href=\"#\">登录</a></li>\r\n                    </ul>\r\n                    <!--头部小导航结束-->\r\n                    <!-- logo -->\r\n                    <h1 class=\"logo clear fl\">\r\n                        <a href=\"index.html\">\r\n                            <img src=\"images/logo.png\" />\r\n                        </a>\r\n                    </h1>\r\n                    <!-- 购物车 -->\r\n                    <div class=\"minicart\">\r\n                        <a class=\"minicart_link\" href=\"#\">\r\n");
      out.write("                            <span class=\"item\"> <b>2</b>\r\n                                件/\r\n                            </span>\r\n                            <span class=\"price\"> <b>￥199.80</b>\r\n                            </span>\r\n                        </a>\r\n                    </div>\r\n                    <!-- 购物车结束 -->\r\n                    <!-- 搜索框 -->\r\n                    <div class=\"header_search\">\r\n                        <div class=\"form-search \">\r\n                            <input  value=\"请输入商品名称\" class=\"input-text\"  type=\"text\"/>\r\n                            <button type=\"submit\" title=\"Search\"></button>\r\n                        </div>\r\n                    </div>\r\n                </div>\r\n            </div>\r\n        </div>\r\n        <!-- 头部结束 -->\r\n        <!-- 导航栏 -->\r\n        <div class=\"navigation_container\">\r\n            <!---->\r\n            <div class=\"nav\">\r\n                <ul class=\"primary_nav\">\r\n                    <li class=\"active highlight\">\r\n                        <a href=\"#\">女装</a>\r\n                        <!--二级菜单-->\r\n");
      out.write("                        <ul class=\"sub_menu\">\r\n                            <li >\r\n                                <a href=\"#\">裙装</a>\r\n                                <ul>\r\n                                    <li>\r\n                                        <a href=\"#\">短裙</a>\r\n                                    </li>\r\n                                    <li>\r\n                                        <a href=\"#\">短裤</a>\r\n                                    </li>\r\n                                    <li>\r\n                                        <a href=\"#\">裤子</a>\r\n                                    </li>\r\n                                    <li>\r\n                                        <a href=\"#\">卡其裤</a>\r\n                                    </li>\r\n                                    <li>\r\n                                        <a href=\"#\">休闲裤</a>\r\n                                    </li>\r\n                                    <li>\r\n                                        <a href=\"#\">牛仔裤</a>\r\n                                    </li>\r\n");
      out.write("                                    <li>\r\n                                        <a href=\"#\">风衣  运动夹克</a>\r\n                                    </li>\r\n                                </ul>\r\n                            </li>\r\n                            <li>\r\n                                <a href=\"#\">装饰品</a>\r\n                                <ul>\r\n                                    <li>\r\n                                        <a href=\"#\">太阳镜</a>\r\n                                    </li>\r\n                                    <li>\r\n                                        <a href=\"#\">围巾</a>\r\n                                    </li>\r\n                                    <li>\r\n                                        <a href=\"#\">发饰品</a>\r\n                                    </li>\r\n                                    <li>\r\n                                        <a href=\"#\">帽子和手套</a>\r\n                                    </li>\r\n                                    <li>\r\n                                        <a href=\"#\">生活时尚</a>\r\n");
      out.write("                                    </li>\r\n                                    <li>\r\n                                        <a href=\"#\">牛仔系列</a>\r\n                                    </li>\r\n                                    <li>\r\n                                        <a href=\"#\">风衣  西服</a>\r\n                                    </li>\r\n                                </ul>\r\n                            </li>\r\n                        </ul>\r\n                    </li>\r\n                    <!--二级菜单结束-->\r\n                    <li>\r\n                        <a href=\"#\">男装</a>\r\n                        <!--二级菜单-->\r\n                        <ul class=\"sub_menu\">\r\n                            <li>\r\n                                <a href=\"#\">男士夏装</a>\r\n                                <ul>\r\n                                    <li>\r\n                                        <a href=\"#\">裤子</a>\r\n                                    </li>\r\n                                    <li>\r\n                                        <a href=\"#\">休闲裤</a>\r\n");
      out.write("                                    </li>\r\n                                    <li>\r\n                                        <a href=\"#\">卡其裤</a>\r\n                                    </li>\r\n                                    <li>\r\n                                        <a href=\"#\">牛仔裤</a>\r\n                                    </li>\r\n                                    <li>\r\n                                        <a href=\"#\">风衣  运动夹克</a>\r\n                                    </li>\r\n                                </ul>\r\n                            </li>\r\n                            <li>\r\n                                <a href=\"#\">装饰品</a>\r\n                                <ul>\r\n                                    <li>\r\n                                        <a href=\"#\">太阳镜</a>\r\n                                    </li>\r\n                                    <li>\r\n                                        <a href=\"#\">围巾</a>\r\n                                    </li>\r\n                                    <li>\r\n                                        <a href=\"#\">发饰品</a>\r\n");
      out.write("                                    </li>\r\n                                    <li>\r\n                                        <a href=\"#\">帽子和手套</a>\r\n                                    </li>\r\n                                    <li>\r\n                                        <a href=\"#\">生活时尚</a>\r\n                                    </li>\r\n                                    <li>\r\n                                        <a href=\"#\">牛仔系列</a>\r\n                                    </li>\r\n                                    <li>\r\n                                        <a href=\"#\">风衣  西服</a>\r\n                                    </li>\r\n                                </ul>\r\n                            </li>\r\n                        </ul>\r\n                        <!--二级菜单结束--> </li>\r\n                    <li>\r\n                        <a href=\"#\">儿童</a>\r\n                    </li>\r\n                    <li>\r\n                        <a href=\"#\">时尚</a>\r\n                    </li>\r\n                    <li>\r\n                        <a href=\"#\">装饰品</a>\r\n");
      out.write("                    </li>\r\n                </ul>\r\n            </div>\r\n        </div>\r\n        <!--导航栏结束-->\r\n        <div class=\"section_container\">\r\n            <!-- 面包屑 -->\r\n            <ul class=\"breadcrumb\">\r\n                <li>\r\n                    <a href=\"#\">首页</a>\r\n                </li>\r\n                <li>\r\n                    <a href=\"#\">女装</a>\r\n                </li>\r\n                <li class=\"active\">\r\n                    <a href=\"#\">长裙</a>\r\n                </li>\r\n            </ul>\r\n            <!-- 产品详情 -->\r\n            <div id=\"product_detail\">\r\n                <!--详情左侧-->\r\n                <div class=\"product_leftcol fl\">\r\n                    <div id=\"jingdong\">\r\n                        <div class=\"datu\">\r\n                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${shop}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/files/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.pic}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n                            <div id=\"fangdajing\"></div>\r\n                        </div>\r\n                        <div class=\"xiaotu\">\r\n                            <div class=\"leftbut\"></div>\r\n                            <div class=\"tu\">\r\n                                <ul>\r\n                                    <li>\r\n                                        <img src=\"images/0.png\" />\r\n                                    </li>\r\n                                    <li>\r\n                                        <img src=\"images/1.png\" />\r\n                                    </li>\r\n                                    <li>\r\n                                        <img src=\"images/2.png\" />\r\n                                    </li>\r\n                                    <li>\r\n                                        <img src=\"images/3.png\" />\r\n                                    </li>\r\n                                    <li>\r\n                                        <img src=\"images/4.png\" />\r\n                                    </li>\r\n");
      out.write("                                    <li>\r\n                                        <img src=\"images/5.png\" />\r\n                                    </li>\r\n                                    <li>\r\n                                        <img src=\"images/6.png\" />\r\n                                    </li>\r\n                                    <li>\r\n                                        <img src=\"images/7.png\" />\r\n                                    </li>\r\n                                    <li>\r\n                                        <img src=\"images/8.png\" />\r\n                                    </li>\r\n                                </ul>\r\n                            </div>\r\n                            <div class=\"rightbut\"></div>\r\n                        </div>\r\n                    </div>\r\n                </div>\r\n                <!--详情左侧结束-->\r\n                <!--详情右侧-->\r\n                <div class=\"product_rightcol fr\">\r\n                    <div id=\"name\">\r\n                        <h1>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.name}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("</h1> <strong>支持货到付款，新店开张，全场低至三折包邮，已购买运费险，七天无理由退换，让您购物无忧！</strong>\r\n                    </div>\r\n                    <ul id=\"summary\">\r\n                        <li id=\"summary-market\">\r\n                            <div class=\"dt\">参&nbsp;考&nbsp;价：</div>\r\n                            <div class=\"dd\"> <del id=\"page_maprice\">￥219.00</del>\r\n                            </div>\r\n                        </li>\r\n                        <li id=\"summary-price\">\r\n                            <div class=\"dt\">折&nbsp;后&nbsp;价：</div>\r\n                            <div class=\"dd\"> <strong class=\"p-price\" id=\"jd-price\">￥");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.price}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("</strong>\r\n                            </div>\r\n                        </li>\r\n                    </ul>\r\n                    <ul id=\"choose\" >\r\n                        <li id=\"choose-color\" class=\"choose-color-shouji\">\r\n                            <div class=\"dt\">选择颜色：</div>\r\n                            <div class=\"dd\">\r\n                                <div class=\"item\">\r\n                                    <b></b>\r\n                                    <a href=\"#none\" title=\"白色\">\r\n                                        <img data-img=\"1\" src=\"images/11.jpg\" width=\"25\" height=\"25\" alt=\"白色 \"> <i>白色</i>\r\n                                    </a>\r\n                                </div>\r\n                                <div class=\"item  selected\">\r\n                                    <b></b>\r\n                                    <a href=\"#none\" title=\"黑色\">\r\n                                        <img data-img=\"1\" src=\"images/22.jpg\" width=\"25\" height=\"25\" alt=\"黑色 \"> <i>黑色</i>\r\n                                    </a>\r\n");
      out.write("                                </div>\r\n                            </div>\r\n                        </li>\r\n                        <li id=\"choose-version\">\r\n                            <div class=\"dt\">选择尺码：</div>\r\n                            <div class=\"dd\">\r\n                                <div class=\"item\">\r\n                                    <b></b>\r\n                                    <a href=\"#none\" title=\"S\" style=\"cursor: pointer;\">S</a>\r\n                                </div>\r\n                                <div class=\"item  selected\">\r\n                                    <b></b>\r\n                                    <a href=\"#none\" title=\"M\" style=\"cursor: pointer;\">M</a>\r\n                                </div>\r\n                                <div class=\"item\">\r\n                                    <b></b>\r\n                                    <a href=\"#none\" title=\"L\" style=\"cursor: pointer;\">L</a>\r\n                                </div>\r\n                                <div class=\"item\">\r\n                                    <b></b>\r\n");
      out.write("                                    <a href=\"#none\" title=\"XL\" style=\"cursor: pointer;\">XL</a>\r\n                                </div>\r\n                                <div class=\"item\">\r\n                                    <b></b>\r\n                                    <a href=\"#none\" title=\"XXL\" style=\"cursor: pointer;\">XXL</a>\r\n                                </div>\r\n                            </div>\r\n                        </li>\r\n                        <li id=\"choose-amount\">\r\n                            <div class=\"dt\">购买数量：</div>\r\n                            <div class=\"dd\">\r\n\t\t\t\t\t\t\t\t <input value=\"1\" size=\"2\" >\r\n                            </div>\r\n                        </li>\r\n                    </ul>\r\n                    <div class=\"add_to_buttons\">                   \r\n                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${shop}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/sorder_addSorder.action?product.id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.id}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n                        \t<button class=\"add_cart\">加入购物车</button>\r\n                        </a>\r\n                        \r\n                    </div>\r\n                </div>\r\n                <!--详情右侧结束--> </div>\r\n            <!--产品详情结束-->\r\n            <!-- 产品列表 -->\r\n            <div class=\"products_list products_slider clear\">\r\n                <h2 class=\"sub_title\">新品发售</h2>\r\n                <ul id=\"first-carousel\" class=\"first-and-second-carousel jcarousel-skin-tango\">\r\n                    <li>\r\n                        <a  href=\"#\"class=\"product_image\">\r\n                            <img src=\"images/pr_l_1.jpg\" />\r\n                        </a>\r\n                        <div class=\"product_info\">\r\n                            <h3>\r\n                                <a href=\"#\">夏季新品长裙</a>\r\n                            </h3>\r\n                            <small>印花 纯棉</small>\r\n                        </div>\r\n                        <div class=\"price_info\">\r\n                        <button>\r\n                            <span class=\"pr_add\">添加购物车</span>\r\n");
      out.write("                        </button>\r\n                        <button class=\"price_add\" title=\"\" type=\"button\"></button>\r\n                            <span class=\"pr_price\">￥76.00</span>\r\n                        </div>\r\n                    </li>\r\n                    <li>\r\n                        <a   href=\"#\" class=\"product_image\">\r\n                            <img src=\"images/pr_l_2.jpg\" />\r\n                        </a>\r\n                        <div class=\"product_info\">\r\n                            <h3>\r\n                                <a href=\"#\">夏季新品长裙</a>\r\n                            </h3>\r\n                            <small>印花 纯棉</small>\r\n                        </div>\r\n                        <div class=\"price_info\">\r\n                            <button>\r\n                                <span class=\"pr_add\">添加购物车</span>\r\n                            </button>\r\n                            <button class=\"price_add\" title=\"\" type=\"button\">\r\n                                <span class=\"pr_price\">￥76.00</span>\r\n");
      out.write("                            </button>\r\n                        </div>\r\n                    </li>\r\n                    <li>\r\n                        <a  href=\"#\" class=\"product_image\">\r\n                            <img src=\"images/pr_l_3.jpg\" />\r\n                        </a>\r\n                        <div class=\"product_info\">\r\n                            <h3>\r\n                                <a href=\"#\">夏季新品长裙</a>\r\n                            </h3>\r\n                            <small>印花 纯棉</small>\r\n                        </div>\r\n                        <div class=\"price_info\">\r\n                            <button>\r\n                                <span class=\"pr_add\">添加购物车</span>\r\n                            </button>\r\n                            <button class=\"price_add\" title=\"\" type=\"button\">\r\n                                <span class=\"pr_price\">￥76.00</span>\r\n                            </button>\r\n                        </div>\r\n                    </li>\r\n                    <li>\r\n                        <a  href=\"#\" class=\"product_image\">\r\n");
      out.write("                            <img src=\"images/pr_l_5.jpg\" />\r\n                        </a>\r\n                        <div class=\"product_info\">\r\n                            <h3>\r\n                                <a href=\"#\">夏季新品长裙</a>\r\n                            </h3>\r\n                            <small>印花 纯棉</small>\r\n                        </div>\r\n                        <div class=\"price_info\">\r\n                            <button>\r\n                                <span class=\"pr_add\">添加购物车</span>\r\n                            </button>\r\n                            <button class=\"price_add\" title=\"\" type=\"button\">\r\n                                <span class=\"pr_price\">￥76.00</span>\r\n                            </button>\r\n                        </div>\r\n                    </li>\r\n                    <li>\r\n                        <a  href=\"#\" class=\"product_image\">\r\n                            <img src=\"images/pr_l_1.jpg\" />\r\n                        </a>\r\n                        <div class=\"product_info\">\r\n                            <h3>\r\n");
      out.write("                                <a href=\"#\">夏季新品长裙</a>\r\n                            </h3>\r\n                            <small>印花 纯棉</small>\r\n                        </div>\r\n                        <div class=\"price_info\">\r\n                            <button>\r\n                                <span class=\"pr_add\">添加购物车</span>\r\n                            </button>\r\n                            <button class=\"price_add\" title=\"\" type=\"button\">\r\n                                <span class=\"pr_price\">￥76.00</span>\r\n                            </button>\r\n                        </div>\r\n                    </li>\r\n                    <li>\r\n                        <a  href=\"#\" class=\"product_image\">\r\n                            <img src=\"images/pr_l_2.jpg\" />\r\n                        </a>\r\n                        <div class=\"product_info\">\r\n                            <h3>\r\n                                <a href=\"#\">夏季新品长裙</a>\r\n                            </h3>\r\n                            <small>印花 纯棉</small>\r\n                        </div>\r\n");
      out.write("                        <div class=\"price_info\">\r\n                            <button>\r\n                                <span class=\"pr_add\">添加购物车</span>\r\n                            </button>\r\n                            <button class=\"price_add\" title=\"\" type=\"button\">\r\n                                <span class=\"pr_price\">￥76.00</span>\r\n                            </button>\r\n                        </div>\r\n                    </li>\r\n                </ul>\r\n            </div>\r\n            <!--产品列表结束  -->\r\n            <!-- 产品列表 -->\r\n            <div class=\"products_list products_slider clear\">\r\n                <h2 class=\"sub_title\">新品发售</h2>\r\n                <ul id=\"first-carousel\" class=\"first-and-second-carousel jcarousel-skin-tango\">\r\n                    <li>\r\n                        <a  href=\"#\" class=\"product_image\">\r\n                            <img src=\"images/pr_l_1.jpg\" />\r\n                        </a>\r\n                        <div class=\"product_info\">\r\n                            <h3>\r\n                                <a href=\"#\">夏季新品长裙</a>\r\n");
      out.write("                            </h3>\r\n                            <small>印花 纯棉</small>\r\n                        </div>\r\n                        <div class=\"price_info\">\r\n                        <button>\r\n                            <span class=\"pr_add\">添加购物车</span>\r\n                        </button>\r\n                        <button class=\"price_add\" title=\"\" type=\"button\">\r\n                            <span class=\"pr_price\">￥76.00</span></button>\r\n                        </div>\r\n                    </li>\r\n                    <li>\r\n                        <a  href=\"#\" class=\"product_image\">\r\n                            <img src=\"images/pr_l_2.jpg\" />\r\n                        </a>\r\n                        <div class=\"product_info\">\r\n                            <h3>\r\n                                <a href=\"#\">夏季新品长裙</a>\r\n                            </h3>\r\n                            <small>印花 纯棉</small>\r\n                        </div>\r\n                        <div class=\"price_info\">\r\n                            <button>\r\n");
      out.write("                                <span class=\"pr_add\">添加购物车</span>\r\n                            </button>\r\n                            <button class=\"price_add\" title=\"\" type=\"button\">\r\n                                <span class=\"pr_price\">￥76.00</span>\r\n                            </button>\r\n                        </div>\r\n                    </li>\r\n                    <li>\r\n                        <a  href=\"#\" class=\"product_image\">\r\n                            <img src=\"images/pr_l_3.jpg\" />\r\n                        </a>\r\n                        <div class=\"product_info\">\r\n                            <h3>\r\n                                <a href=\"#\">夏季新品长裙</a>\r\n                            </h3>\r\n                            <small>印花 纯棉</small>\r\n                        </div>\r\n                        <div class=\"price_info\">\r\n                            <button>\r\n                                <span class=\"pr_add\">添加购物车</span>\r\n                            </button>\r\n                            <button class=\"price_add\" title=\"\" type=\"button\">\r\n");
      out.write("                                <span class=\"pr_price\">￥76.00</span>\r\n                            </button>\r\n                        </div>\r\n                    </li>\r\n                    <li>\r\n                        <a  href=\"#\" class=\"product_image\">\r\n                            <img src=\"images/pr_l_5.jpg\" />\r\n                        </a>\r\n                        <div class=\"product_info\">\r\n                            <h3>\r\n                                <a href=\"#\">夏季新品长裙</a>\r\n                            </h3>\r\n                            <small>印花 纯棉</small>\r\n                        </div>\r\n                        <div class=\"price_info\">\r\n                            <button>\r\n                                <span class=\"pr_add\">添加购物车</span>\r\n                            </button>\r\n                            <button class=\"price_add\" title=\"\" type=\"button\">\r\n                                <span class=\"pr_price\">￥76.00</span>\r\n                            </button>\r\n                        </div>\r\n                    </li>\r\n");
      out.write("                    <li>\r\n                        <a  href=\"#\" class=\"product_image\">\r\n                            <img src=\"images/pr_l_1.jpg\" />\r\n                        </a>\r\n                        <div class=\"product_info\">\r\n                            <h3>\r\n                                <a href=\"#\">夏季新品长裙</a>\r\n                            </h3>\r\n                            <small>印花 纯棉</small>\r\n                        </div>\r\n                        <div class=\"price_info\">\r\n                            <button>\r\n                                <span class=\"pr_add\">添加购物车</span>\r\n                            </button>\r\n                            <button class=\"price_add\" title=\"\" type=\"button\">\r\n                                <span class=\"pr_price\">￥76.00</span>\r\n                            </button>\r\n                        </div>\r\n                    </li>\r\n                    <li>\r\n                        <a  href=\"#\" class=\"product_image\">\r\n                            <img src=\"images/pr_l_2.jpg\" />\r\n");
      out.write("                        </a>\r\n                        <div class=\"product_info\">\r\n                            <h3>\r\n                                <a href=\"#\">夏季新品长裙</a>\r\n                            </h3>\r\n                            <small>印花 纯棉</small>\r\n                        </div>\r\n                        <div class=\"price_info\">\r\n                            <button>\r\n                                <span class=\"pr_add\">添加购物车</span>\r\n                            </button>\r\n                            <button class=\"price_add\" title=\"\" type=\"button\">\r\n                                <span class=\"pr_price\">￥76.00</span>\r\n                            </button>\r\n                        </div>\r\n                    </li>\r\n                </ul>\r\n            </div>\r\n            <!--产品列表结束  -->\r\n            <!-- 导航栏结束 -->\r\n            <div class=\"footer_container\">\r\n                <div class=\"footer\">\r\n                    <ul class=\"footer_links\">\r\n                        <li>\r\n                            <span>收藏本店</span>\r\n");
      out.write("                            <ul>\r\n                                <li>\r\n                                    <a href=\"#\">服装</a>\r\n                                </li>\r\n                                <li>\r\n                                    <a href=\"#\">鞋子</a>\r\n                                </li>\r\n                                <li>\r\n                                    <a href=\"#\">包包</a>\r\n                                </li>\r\n                                <li>\r\n                                    <a href=\"#\">装饰品</a>\r\n                                </li>\r\n                                <li>\r\n                                    <a href=\"#\">channel</a>\r\n                                </li>\r\n                                <li>\r\n                                    <a href=\"#\">prada</a>\r\n                                </li>\r\n                                <li>\r\n                                    <a href=\"#\">LV</a>\r\n                                </li>\r\n                            </ul>\r\n                        </li>\r\n");
      out.write("                        <li class=\"seperator\">\r\n                            <span>出售的品牌</span>\r\n                            <ul>\r\n                                <li>\r\n                                    <a href=\"#\">Elle</a>\r\n                                </li>\r\n                                <li>\r\n                                    <a href=\"#\">Reallxe</a>\r\n                                </li>\r\n                                <li>\r\n                                    <a href=\"#\">Fabric</a>\r\n                                </li>\r\n                                <li>\r\n                                    <a href=\"#\">Mayflower</a>\r\n                                </li>\r\n                                <li>\r\n                                    <a href=\"#\">Levis Strauss</a>\r\n                                </li>\r\n                                <li>\r\n                                    <a href=\"#\">Anzonica</a>\r\n                                </li>\r\n                                <li>\r\n                                    <a href=\"#\">Reallxe</a>\r\n");
      out.write("                                </li>\r\n                                <li>\r\n                                    <a href=\"#\">Fabric</a>\r\n                                </li>\r\n                            </ul>\r\n                        </li>\r\n                        <li>\r\n                            <span>客户服务</span>\r\n                            <ul>\r\n                                <li>\r\n                                    <a href=\"#\">帮助</a>\r\n                                </li>\r\n                                <li>\r\n                                    <a href=\"#\">速递</a>\r\n                                </li>\r\n                                <li>\r\n                                    <a href=\"#\">退换货</a>\r\n                                </li>\r\n                                <li>\r\n                                    <a href=\"#\">付款方式</a>\r\n                                </li>\r\n                                <li>\r\n                                    <a href=\"#\">订单跟踪</a>\r\n                                </li>\r\n                                <li>\r\n");
      out.write("                                    <a href=\"#\">礼物包选项</a>\r\n                                </li>\r\n                                <li>\r\n                                    <a href=\"#\">国际服务</a>\r\n                                </li>\r\n                                <li>\r\n                                    <a href=\"#\">退运险</a>\r\n                                </li>\r\n                            </ul>\r\n                        </li>\r\n                        <li>\r\n                            <span>个人账户</span>\r\n                            <ul>\r\n                                <li>\r\n                                    <a href=\"#\">个人账户信息</a>\r\n                                </li>\r\n                                <li>\r\n                                    <a href=\"#\">用户密码</a>\r\n                                </li>\r\n                                <li>\r\n                                    <a href=\"#\">订单历史</a>\r\n                                </li>\r\n                                <li>\r\n                                    <a href=\"#\">付款方式</a>\r\n");
      out.write("                                </li>\r\n                                <li>\r\n                                    <a href=\"#\">我的收货地址</a>\r\n                                </li>\r\n                                <li>\r\n                                    <a href=\"#\">我的通知</a>\r\n                                </li>\r\n                            </ul>\r\n                        </li>\r\n                    </ul>\r\n                </div>\r\n            </div>\r\n         </div>\r\n      </div>\r\n\t</body>\r\n</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(PageContext _jspx_page_context)
          throws Throwable {
    PageContext pageContext = _jspx_page_context;
    JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /public/head.jspf(4,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.Object.class, (PageContext)_jspx_page_context, null, false));
    // /public/head.jspf(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("shop");
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }
}
